### ISSUE TITLE
Копировать адрес для гугл привязки

### ISSUE THREAD

**Issue by EdjOne** [AntonShevchuk/wme-e50#1]
Добавить функционал, при выделении ПОИ со всеми атрибутами, данные копуруются в буфер, чтоб потом вставить в гуглоприязку.

**Comment by AntonShevchuk** [comment]
При выделении чревато последствиями, когда копируешь из внешнего источника какую-либо инфу о POI (например адрес сайта), то буфер будет перетёрт, пока сделал по клику на данные полученные с внешних сервисов.

**Comment by AntonShevchuk** [comment]
Может имеет смысл сделать какой-то hotkey для копирования текущих данных для привязки? Может у PIE даже есть такое :)

**Comment by AntonShevchuk** [comment]
Автоматическое копирование в буфер надо вынести в настройки

**Comment by renardua** [comment]
На самом деле тут все просто и хитро.
Достаточно ввести первые 3 символа адреса и первый в списке должен быть гугл.
Предлагаю алгоритм:
1. если номер дома больше 2 символов - в буфер копировать 3 символа (например, 121, 12А, 12/2)
2. если номер дома больше 1 символа - в буфер копировать 2 символа и пробел (например, "12 ", "1А ")
3. если номер дома из 1 символа - в буфер копировать 1 символ, пробел и первую букву улицы (например, "1 П", "8 С")

**Comment by AntonShevchuk** [comment]
@renardua так будет работать, только если мы осуществляем привязку к адресу

**Comment by AntonShevchuk** [comment]
Добавлен hotkey при выделении POI - `Ctrl`+`B`
