### ISSUE TITLE
Check city

### ISSUE THREAD

**Issue by SapozhnikUA** [AntonShevchuk/wme-e50#11]
https://i.imgur.com/wcEj59B.jpg
![wcEj59B 1](https://user-images.githubusercontent.com/48523324/64472502-26d7ed80-d168-11e9-8764-23d96f66f9cd.jpg)

Здесь можно потестировать
https://www.waze.com/uk/editor/?env=row&lon=23.84537&lat=49.83545&zoom=7&segments=318073479

**Comment by AntonShevchuk** [comment]
Тут можно сделать следующее, если в области редактирования только один НП, то использовать его для всех POI, игнорируя данные с внешних ресурсов, т.к. в данном примере я тут никак не угадаю название.

**Comment by SapozhnikUA** [comment]
Может сравнивать НП, который есть на экране и тот, который предлагают  сторонние сервисы?
В случае, если на экране два-три НП, пои-хелпер предлагал выбрать вариант из двух-трех...

**Comment by AntonShevchuk** [comment]
Я нашёл алгоритм для матчинга названий, попробую с ним.
