### ISSUE TITLE
Точка финиша

### ISSUE THREAD

**Issue by SapozhnikUA** [AntonShevchuk/wme-e50#12]
При создании точки финиша, клонировать координаты ее маркера из источника.

**Comment by SapozhnikUA** [comment]
+ При условии, что она не была создана ранее

**Comment by SapozhnikUA** [comment]
+ использовать только 2гис и ОСМ и возможно Яндекс
+ Функция включается галочкой в настройках.

**Comment by AntonShevchuk** [comment]
Хм, может делать точку по координатам, если она внутри контура? (опционально)
Не привязываясь к тому, кто даёт данные.

**Comment by SapozhnikUA** [comment]
идея хорошая, но мой взгляд корректные данные мало кто дает. Гуглу, Бингу и
Хере точно верить нельзя :)

Andrey Fomenko
Ukraine, Kyiv
sapozhnik@gmail.com


пн, 9 сент. 2019 г. в 15:16, Anton <notifications@github.com>:
