### ISSUE TITLE
неправильный номер в адресе

### ISSUE THREAD

**Issue by SapozhnikUA** [AntonShevchuk/wme-e50#14]
![image](https://user-images.githubusercontent.com/48523324/64475666-484bd000-d18e-11e9-9a65-373c10f89d76.png)

**Comment by AntonShevchuk** [comment]
А на что мы его менять должны - на прочерк: `2А-2`?

**Comment by AntonShevchuk** [comment]
Данный кейс не описан в правилах на wiki
https://wazeopedia.waze.com/wiki/Ukraine/%D0%AF%D0%BA_%D0%BD%D0%B0%D0%B7%D0%B8%D0%B2%D0%B0%D1%82%D0%B8_%D0%B1%D1%83%D0%B4%D0%B8%D0%BD%D0%BA%D0%B8

**Comment by SapozhnikUA** [comment]
Это очень редкий вариант, возможно пропустили. Можно рассматривать как частный случай корпусов
