### ISSUE TITLE
Авто создание новых НП

### ISSUE THREAD

**Issue by SapozhnikUA** [AntonShevchuk/wme-e50#19]
Ужесточить/запретить разрешение смены НП, если полученное от провайдера НП отсутствует в списке вейза. 
иногда на автопилоте можно создать новый НП и не заметить. 
![image](https://github.com/AntonShevchuk/wme-e50/assets/48523324/e303367a-6580-40d2-a535-f2e2afb17ea2)

**Comment by AntonShevchuk** [comment]
Додав ще одне попередження, коли не має такого НП
